version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
      - ./data/log:/data/log
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWD
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /data/log